version: '3'
services:

    php:
        image: php:fpm
        ports:
            - 9000:9000
        volumes:
            - ../src:/var/www/plannit
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ../src:/var/www/plannit
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/error.log:/var/log/nginx/error.log
            - ./nginx/access.log:/var/log/nginx/access.log
        depends_on:
            - php

    # mysql:
    #     image: mysql:latest
    #     ports:
    #         - 3306:3306
    #     depends_on:
    #         - php
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #         MYSQL_DATABASE: ${MYSQL_DATABASE}
    #         MYSQL_USER: ${MYSQL_USER}
    #         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     restart: always
    #     depends_on:
    #         - mysql
    #     ports:
    #         - 8183:80
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #         MYSQL_USER: ${MYSQL_USER}
    #         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
